backend:
  name: git-gateway
  branch: main
publish_mode: editorial_workflow
media_folder: "src/assets/images"
public_folder: "/assets/images"
collections:
  - name: "recipes"
    label: "Recipes"
    folder: "src/recipes"
    slug: "{{slug}}"
    create: true
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "layouts/recipe.njk"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Yield", name: "yield", widget: "string", required: false}
      - {label: "Prep", name: "prep", widget: "string", required: false}
      - {label: "Cook", name: "cook", widget: "string", required: false}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Source", name: "source", widget: "datetime"}
      - {label: "Tag", name: "tag", widget: "string"}
      - {label: "Ingredients", name: "ingredients", widget: "list", allow_add: true}
      - {label: "Body", name: "body", widget: "markdown"}
  - label: "Globals"
    name: "globals"
    files:
      - label: "Site Data"
        name: "site_data"
        delete: false
        file: "src/_data/site.json"
        fields:
          - {label: "site_name", name: "site_name", widget: "string"}
          - {label: "title", name: "title", widget: "string"}
          - {label: "description", name: "description", widget: "string"}
          - {label: "url", name: "url", widget: "string"}
          - {label: "locale", name: "locale", widget: "string"}
          - {label: "author", name: "author", widget: "string"}